### ISSUE TITLE
API is contacted using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by redox** [kissmetrics/kmts#14]
It turns out that the current code forces the API to be contacted as `HTTP`. It should allow (and default to?) HTTPS.

**Comment by percyhanna** [comment]
Hi Sylvain, thanks for adding this issue. We're working to clean up the `kmts` gem a bit, and will also look to default/force HTTPS for all traffic.

**Comment by percyhanna** [comment]
@redox We have just released [Version 3.0.0](https://github.com/kissmetrics/kmts/releases/tag/v3.0.0) of the `kmts` gem. It now defaults to HTTPS tracking. Thanks.

**Comment by redox** [comment]
> @redox We have just released Version 3.0.0 of the kmts gem. It now defaults to HTTPS tracking. Thanks.

Cool :) Gonna have a look!

**Comment by percyhanna** [comment]
Please also note some other changes, most significantly is that cron mode is enabled by default. You can still disable it if desired, but cron/asynchronous tracking is the preferred method.
