### ISSUE TITLE
warning: regexp match /.../n against to UTF-8 string

### ISSUE THREAD

**Issue by andrewhavens** [kissmetrics/kmts#19]
I am using this gem to send data to Kissmetrics, but I often see this warning in my logs:

    ~/.rbenv/versions/2.4.2/lib/ruby/2.4.0/uri/rfc2396_parser.rb:305: warning: regexp match /.../n against to UTF-8 string

I finally figured out that this happens when the data includes some latin character, such as `ñ` because all of the values are encoded as URL query params using `URI.escape`:

    KMTS.record("user-1234", "viewed page", { "viewed page - page_title" => "En Español" })
    # /e?_p=user-1234&_n=viewed%20page&viewed%20page%20-%20page_title=En%20Espa%C3%B1ol

I'm guessing it's related to [this line](https://github.com/kissmetrics/kmts/blob/37470b1fd94d179abd8dc7a9a6bb9f65175d20ba/lib/kmts.rb#L212), but I could be wrong.

My data is in UTF-8 encoding, so I don't think I'm doing anything wrong, but these warnings are concerning because I'm not sure if my data is being sent/received/encoded correctly.

I am using gem version 3.0.2.

**Comment by andrewhavens** [comment]
Actually, the problem seems to be with passing a custom regex, instead of using the regex that URI escape defaults to: https://github.com/kissmetrics/kmts/blob/37470b1fd94d179abd8dc7a9a6bb9f65175d20ba/lib/kmts.rb#L209

Example:
```
require "uri"
string = "En Español"
URI.escape(string)
#=> "En Espa%C3%B1ol"

kmts_regex = Regexp.new("[^#{URI::REGEXP::PATTERN::UNRESERVED}]", false, 'N')
URI.escape(string, kmts_regex)
~/.rbenv/versions/2.4.2/lib/ruby/2.4.0/uri/rfc2396_parser.rb:306: warning: regexp match /.../n against to UTF-8 string
#=> "En Espa%C3%B1ol"
```

**Comment by rawsyntax** [comment]
@andrewhavens thanks for reporting this warning. I'm working on a fix in the above PR

**Comment by rawsyntax** [comment]
@andrewhavens please try out version `3.0.3`

**Comment by andrewhavens** [comment]
@rawsyntax Version 3.0.3 seems to have resolved the warning logs. Thanks!

**Comment by rawsyntax** [comment]
👍
