### ISSUE TITLE
add option to set read_timeout for Net::HTTP

### ISSUE THREAD

**Issue by saneshark** [kissmetrics/kmts#4]
Let me know if you'd like for me to make a pull request. 

Note: If I write test cases they won't test actual timeout windows working obviously, just perhaps that the parameter is set and that there is some sort of sane logging of the error returned (Timeout::Error).

This would be an option passed in at initiation, not when performing an action, for that there's always:

```
begin
   Timeout::timeout(5) do
      KMTS.record(...)
   end
rescue Timeout::Error => e
   ...do something
end
```

**Comment by percyhanna** [comment]
It is recommended that you enable `use_cron` and not track events synchronously in production scenarios.
